os: linux
sudo: false
dist: trusty
addons:
  apt:
    packages:
    - lua5.2
git:
  depth: 5
install:
- npm install
script:
- npm start
- npm run pack
deploy:
  provider: releases
  api_key: "$TOKEN"
  file_glob: true
  file: releases/*
  skip_cleanup: true
  on:
    tags: true
env:
  matrix:
    secure: Blrvj4+Bf9TvsMKNgHzfCti5WNy2yxuxlHikD/PJ99qkP5EAdhdkrt97sdYaiYWqb28nRJPtXCRJDWGuXlRaBjcSo1dee1g8JNdeM7GT3ZElmyp/s24FgjL8EdBZ/sVLe04yioa8743STNNnxlBJ6Nf8woi/fqwXB8/cxGvV+GN8qBdU2wfCZ4BpqGaJ6kFMRigtPVWDfjDda8SFqbLvH9FISHikiflgpEL+Xy8A/EOXEJYS9qsAedZK2X981mqeHsCX5VaGBF02Ly1uCfOWNnJfCjdYKepdL3o8c4XRR40YAmB6eWsjNqzGxj0puR4CzjQnuTlzb1pCZHHc9VPjXZd2OUBIb4gGtyX9UPdA1T4/kxVUmvhFMuMNk0HhsFRD23X1y8AZDRQfjK3LQAXZ2miCSyCxvznzSSMotCd70237m3LIa5E73yiy4c0oak5SnCE7EGm/TFtctOuz94C3IIHZ3lR56PC9Q9WfffuGvHL5Cth585siCj//iyYS4stzgWm8ttsv/F59aG+4TYON8lYXG0oxMgLVjrA/1MgCNVGm6+RZcSBKmDhIA4vxUCoJGBz+EbyQte/bxqNEx3eijZpZIun8Si+u13xCA+1n+SceHz6emtG+JurYZwoUxsivpWySagw51e7RJaNtLExib412ZBtlf5bFl65Xfq9V4nE=
